-- Migration number: 0002 generated by teenybase on 2026-04-11T00:54:09.649Z. Do not modify this file.

CREATE TABLE kv_store (
	key TEXT PRIMARY KEY NOT NULL, 
	value JSON NOT NULL, 
	expire TIMESTAMP
);