-- Migration number: 0002 generated by teenybase on 2026-04-10T23:18:40.138Z. Do not modify this file.

CREATE TABLE kv_store (
	key TEXT PRIMARY KEY NOT NULL, 
	value JSON NOT NULL, 
	expire TIMESTAMP
);