name = "croissante-tts"
main = "src/worker.ts"
compatibility_date = "2024-09-25"
workers_dev = true

[observability]
enabled = true

[[r2_buckets]]
binding = "TTS_CACHE"
bucket_name = "croissante-tts-audio"
